### ISSUE TITLE
iOS issue

### ISSUE THREAD

**Issue by zean00** [tkyaji/cordova-plugin-crypt-file#10]
Hi,

I've been trying to use this plugin for iOS and android, the android works fine, but the iOS won't work, when the apps is running, it's only showing a page with encrypted string on it. I don't know how to trace so I couldn't really know where is the problem.

I'm using cordova 5.4.1 iOS 3.9.2 and com.telerik.plugins.wkwebview plugin

**Comment by zean00** [comment]
It seems that wkwebview plugin cause the plugin not to work, since it's using kind of local web server to work with. when the wkwebview plugin is removed, the plugin works just fine

**Comment by letmaik** [comment]
FYI, this is the official feature request to make custom URL protocol handlers work in WKWebView: https://bugs.webkit.org/show_bug.cgi?id=138169

@tkyaji It should be mentioned on the README that for iOS it only works with UIWebView.

**Comment by akash-pal** [comment]
Any updates on this?
