### ISSUE TITLE
Files not decrypted when app launched. I could see my cordova project file got encrypted but could not launch the application

### ISSUE THREAD

**Issue by DevHybrid** [tkyaji/cordova-plugin-crypt-file#11]
Hi tkyaji,

Thanks for this awesome plugin, much needed for hybrid apps!

I am using cordova-plugin-crypt-file in my project. I have installed the plugin and built cordova android project.
When I checked the source code after building it, the files got successfully encrypted.

But when I run the project (launch on Android device), it gives error of index.html not found.

Please suggest if I am missing on any other configuration or anything needs to be upgraded.
Using cordova version 5.4.0
Ionic version 1.7.10

Please help!!!

**Comment by pallaviMN** [comment]
@DevHybrid , can you please tell me how to call encrypt & decrypt of this plugin. Or Just installation of this is enough?

**Comment by DevHybrid** [comment]
Hi,
I also tried this plugin in one of my apps.
But it supports few android devices and crashes app for others. The development of this plugin is already stopped by tkyaji. So I don’t think it will support future apps.

Regards,
Sumit Dalve
Mobility | Digital Transformation SBU
Phone: +91-20-6652 5000 | Ext: 2048 | Cell: +91-9860350510
————————————————————————————
KPIT | Web: www.kpit.com<http://www.kpit.com/>   Social: Facebook<http://www.kpit.com/facebook> | Twitter<http://www.kpit.com/twitter> | Linkedin<http://www.kpit.com/linkedin> | Youtube<http://www.kpit.com/youtube>

**Comment by pallaviMN** [comment]
@DevHybrid , can you please send code snippet of how to call this plugin in hybrid apps?
