### ISSUE TITLE
What Cordova version does this plugin supports?

### ISSUE THREAD

**Issue by renandecarlo** [tkyaji/cordova-plugin-crypt-file#14]
I couldn't get this plugin to work with Cordova 3.5.0. I think plugin's hooks are not available in this version. There seems to lack some new CordovaResourceApi classes too.

**Comment by tkyaji** [comment]
Sorry. This plugin not be compatible with older cordova versions.

**Comment by renandecarlo** [comment]
I investigated a little further and I think it should work from version 4+ of Cordova. I didn't test though.
Just to inform if someone else needs that.
