### ISSUE TITLE
Using ionic.Platform.ready to get device uuid doesn't run after installing the cordova-plugin-crypt-file plugin

### ISSUE THREAD

**Issue by shariajoe** [tkyaji/cordova-plugin-crypt-file#16]
I have been trying to obtain my **device uuid** for some 2 days now still cant find away through, The code works fine without the plugin and i get the uuid, but once i install it simply doesnt show.
I have isolated the problem to this function **ionic.Platform.ready()** as it is not executed.Kindly help out solve this issue.

Here is the sample code:

```
.run(function($ionicPlatform, $localstorage) {	
    $ionicPlatform.ready(function() {
        if (window.cordova && window.cordova.plugins.Keyboard) {
            cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);
        }
        if (window.StatusBar) {
            StatusBar.styleDefault();
        }
		var device = ionic.Platform.device();
		$localstorage.set('deviceIDs', device.uuid);  
    })	;
})
```

**Comment by zean00** [comment]
If you are using this plugin in android with other cordova plugin, it won't work out of the box. You might want to check similar issue for the workaround  https://github.com/tkyaji/cordova-plugin-crypt-file/issues/12
