### ISSUE TITLE
Can you please send the code to encrypt file

### ISSUE THREAD

**Issue by pallaviMN** [tkyaji/cordova-plugin-crypt-file#17]
Hi,

I am using ionic framework to build a mobile app. I want to encrypt one of my file. Can you please tell me how to call the plugin to encrypt it. Or just installation of the plugin is enough?

**Comment by pallaviMN** [comment]
Can i encrypt files stored in SDCard??

**Comment by tkyaji** [comment]
You can encrypt source files at time of run `cordova build`, just install this plugin.

**Comment by renandecarlo** [comment]
If you want to encrypt a single file, [this plugin](https://github.com/disusered/cordova-safe) might work better. Note though, that if your source javascript is not encrypted, the key to encrypt these files will be available anyhow.
