### ISSUE TITLE
Not working perferctly with ionic app.

### ISSUE THREAD

**Issue by Neotrixsx** [tkyaji/cordova-plugin-crypt-file#18]
I try your plugin in my ionic application after install crypt plugin in my app not show any data in display on screen. My app shows only white screen.

![screenshot_2016-06-14-12-17-11](https://cloud.githubusercontent.com/assets/7522102/16033558/4aa9479e-322a-11e6-8203-951c6023af98.png)

**Comment by pallaviMN** [comment]
@Neotrixsx , can you please let me know how can we use the plugin in ionic, i need sample code snippet of it.

**Comment by mghayour** [comment]
its not working on ionic.
same problem
what shouldwe do !?

**Comment by mghayour** [comment]
i'm working on simple ionic project for test this plugin and find problem
but its working whithout any problem !
i should recheck my main project codes to finding problem ...
i will share result, thank you

**Comment by tkyaji** [comment]
Please try version 1.1.3.

**Comment by Neotrixsx** [comment]
Really Awesome Plugin. :+1: :100: 
Now its working fine with IOINC ver.1 Apps

**Comment by eddskt** [comment]
This is a wonderful plugin.
I really do not want to trade it for any other in my project.
but ... 
I'm having the white screen problem. Version 1.3.2
Only on a specific page. This page loads jQuery mobile, the only difference from the others.
When locking a screen, and unlocking a tea makes the cell phone, the application comes back with a white screen, showing the encrypted code.

My <head>:

Assets / css / bootstrap.min.css
Assets / css / font-awesome.min.css
Assets / css / base.css
Assets / css / style.css
Assets / css / custom.css
Assets / css / bootstrap-tour.min.css
Assets / appjs / commonFuncs.js
Assets / appjs / apiFuncs.js
Assets / appjs / dbFuncs.js
Assets / appjs / apiCommands.js
Assets / appjs / fastclick.js
Assets / js / bootstrap-tour.min.js

@tkyaji
