### ISSUE TITLE
Ayuda como puedo utilizar este plugin?

### ISSUE THREAD

**Issue by wuilmerj24** [tkyaji/cordova-plugin-crypt-file#24]
Hola quiero encriptar una carpeta, como puedo utilizar este plugin?

**Comment by videmort** [comment]
Debes de añadir el plugin
cordova plugin add cordova-plugin-crypt-file
una vez que lo añadas cuando compiles automáticamente encriptara tus archivos. Es útil cuando subes a producción una app. Mientras estás desarrollando no deberías usarlo pues no podrás debuggear en el dispositivo.
Un saludo

@tkyaji you can close this issue :)

**Comment by tkyaji** [comment]
@videmort thanks!
