### ISSUE TITLE
CRYPT_KEY

### ISSUE THREAD

**Issue by ferninver92** [tkyaji/cordova-plugin-crypt-file#26]
Hi, I've a question..

How is generated the CRYPT_KEY ? It's always "" ? or a random value?

Thanks!

**Comment by renandecarlo** [comment]
It generates a random key upon compiling

**Comment by tkyaji** [comment]
Yes. It will be generated when you run `cordova build` command.

**Comment by ferninver92** [comment]
Thanks!
