### ISSUE TITLE
Header fileld problem when i use this crypt plugin

### ISSUE THREAD

**Issue by videmort** [tkyaji/cordova-plugin-crypt-file#28]
Hello, when I install this plugin I got this error in some http request
Request header field sessionIdsTT is not allowed by Access-Control-Allow-Headers. 

I use Ionic and AngularJS. 

Any idea to fix that? Only Happen in Android, in iOS works well.

Thanks

**Comment by renandecarlo** [comment]
You need to have cross origin header on the server side, otherwise it won't work. At least for XHR requests I think.
