### ISSUE TITLE
Not working on iOS 8.14 and iOS 9 beta

### ISSUE THREAD

**Issue by JoergHolz** [tkyaji/cordova-plugin-crypt-file#3]
Great plugin, thank you very much. It works on Android (Just tested it on 5.1.1) very well, but on iOS it is not decrypting the js file. It just shows the encrypted code. I tried it with iOS 8.14, iOS 9 beta, XCode 6.4 and XCode 7 beta 5.

I got no error messages.

**Comment by tkyaji** [comment]
I tested iOS8.4, Xcode6.4, but have not tried on iOS9 yet.
Could you try "cordova emulate" command.
Please tell me whether an error occurs by following procedure.

1. `cordova platform add ios`
2. `cordova plugin add cordova-plugin-crypt-file`
3. `cordova build ios`
4. `cordova emulate ios`
5. build on XCode

**Comment by JoergHolz** [comment]
It works, my mistake!

I was fixed on my normal developer way, which means, that I don't use the cordova build and emulate things - sorry.

Do you know, that your plugin could be groundbreaking? Have you tried to go in contact with the cordova people?

**Comment by tkyaji** [comment]
I see that.

Please tell me if you know a good way to spread the plugin.

**Comment by Sanafan** [comment]
I think the same as you Joerg, so i would just link @agrieve and i think he's going to take a look at this one. It works great and it is very easy to use. I would recommend to add this into the documentation on cordova.apache.org.

**Comment by JoergHolz** [comment]
@tkyaji: I think, a first step could be to go in contact with the developer of cordova, You find the mail list address on cordova.apache.org. That are very nice people and good developers. (I'm also in the list, but I'm more the commenter from the cordova user site.)

The point is, that the cordova developer trying to implement as much open standards as possible, so your plugin is a little bit of contra to this idea. However: From a user site, there are sometime needs, to crypt informations or code. So that will be an interesting discussion. ;-))

On the other hands, there are some plans to relaunch the documantion pages of cordova and give the developers more help and showing best practices. So that will be a good place or your plugin.

And there will be a cordova developer meeting on 16th (?) of october in california.

**Comment by JoergHolz** [comment]
@Sanafan: Good idea, thx.
