### ISSUE TITLE
Support for Windows platform

### ISSUE THREAD

**Issue by hanthomas** [tkyaji/cordova-plugin-crypt-file#30]
I'm not sure if this is even possible, but it would nice if this supported Windows platform.  I know that Cordova for Windows is simply a wrapper for WinJS, so it would probably depend upon whether or not WinJS allows overriding URI remap and file IO handling.

**Comment by tkyaji** [comment]
Sorry, I have no plan to support for Windows at the moment.
welcome pull requests.

**Comment by arcadius** [comment]
Windows support would be much appreciated :+1:
