### ISSUE TITLE
Not working with cordova 6.4

### ISSUE THREAD

**Issue by videmort** [tkyaji/cordova-plugin-crypt-file#33]
Plugin can not be installed in cordova 6.4 (last available version sudo npm install -g cordova)

**Comment by renandecarlo** [comment]
It works under 6.3.1. If that a must-have for your project, you might consider downgrading in the meanwhile

**Comment by tkyaji** [comment]
I've tried with cordova 6.4, but was working normally. Please tell me in detail the error.

**Comment by videmort** [comment]
mmmmm have you been updated the cordova platform too?  cordova platform update ....?

**Comment by tkyaji** [comment]
I ran the following.

```
$ sudo npm install -g cordova
```

```
$ cordova -version
> 6.4.0
```

**Comment by videmort** [comment]
Is working now :S maybe a cordova platform issue
