### ISSUE TITLE
Encrypt plugin fail

### ISSUE THREAD

**Issue by videmort** [tkyaji/cordova-plugin-crypt-file#34]
Is possible to no crypt cordova plugins? Only my code no 3rd parties plugins?
I'm getting some issues with that

**Comment by videmort** [comment]
I want to crypt only that files for example platforms/ios/www/js but not --> platforms/ios/www/plugins

**Comment by videmort** [comment]
3rd Parties plugins works fine in iOS but in android if one plugin have got html inside, it doesn't decrypt well.

**Comment by tkyaji** [comment]
You can specify encryption files in 1.3.0. Please refer to the following.
https://github.com/tkyaji/cordova-plugin-crypt-file#edit-subjects
