### ISSUE TITLE
HTML not decrypted after reload

### ISSUE THREAD

**Issue by blaskurain** [tkyaji/cordova-plugin-crypt-file#35]
Hi,

I have detected that when I execute this in Javascript:

`window.location.reload()`

After reloading the raw html file (encrypted) gets displayed instead of the decrypted version. I managed to work around the problem by doing this instead:

`window.location = window.location.href.replace(/#.*/, '');`

I believe the problem might be isCryptFiles. It doesn't take into account that the URI might have a fragment identifier and it doesn't look like this situation is handled anywhere else.

**Comment by tkyaji** [comment]
Is the environment Android?
Please try the latest version.

**Comment by blaskurain** [comment]
The environment was indeed Android. I am sorry but I can't try the latest version: the project on which the problem was detected is already closed and I'm too busy right now to take it back.

**Comment by tkyaji** [comment]
OK. Close this issue.

**Comment by ibrahimAboelsuod** [comment]
I have this issue with the latest version. And blaskurain  workaround didn't work for me.
What I am trying to do is to reload the app when the user logs out. and it loads the index.html file but encrypted !
