### ISSUE TITLE
Exclude Extensions

### ISSUE THREAD

**Issue by rgfpy** [tkyaji/cordova-plugin-crypt-file#38]
How to exclude extension to ecrypt?

Example: I just want to encrypt ".js"

I tried in but not work
private static final String[] CRYPT_FILES = {
        ".js",
    };

**Comment by tkyaji** [comment]
It supported with 1.3.0. Please refer to the following.
https://github.com/tkyaji/cordova-plugin-crypt-file#edit-subjects
