### ISSUE TITLE
Problem with CORS

### ISSUE THREAD

**Issue by gerbil** [tkyaji/cordova-plugin-crypt-file#4]
`I/chromium(24780): [INFO:CONSOLE(0)] "XMLHttpRequest cannot load http://backend:11000/login. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost' is therefor
e not allowed access. The response had HTTP status code 404.", source: http://localhost/index.html#/ (0)`

Without plugin everything working fine. Access-Control-Allow-Origin is present in response header, i've checked that from two devices & pc. Seems like config.xml is not working like it should or some other stuff..

**Comment by tkyaji** [comment]
In the case of android, it will be run as localhost. Therefore, you need to allow localhost in Access-Control-Allow-Origin.
