### ISSUE TITLE
ionic 3 showing error src/android/com/tkyaji/cordova/DecryptResource.java not found

### ISSUE THREAD

**Issue by manojbhardwaj** [tkyaji/cordova-plugin-crypt-file#65]
ionic 3 showing error src/android/com/tkyaji/cordova/DecryptResource.java not found

Hi thank you for this cordova-plugin-crypt-file plugin a few day ago I used this plugin into my many projects and it's working good but today I create new project with ionic 2 and add android platform after that I try to used your plugin and on create build time it's first showing encrypt process and encrypt all html css and javascript file but after that it's showing me error on terminal with  src/android/com/tkyaji/cordova/DecryptResource.java not found  not found and my build process is stops and also hooks are not created on ionic 3 latest project

**Comment by FinlayDaG33k** [comment]
I'm also affected by this, using plain Cordova

**Comment by manojbhardwaj** [comment]
Thank you  FinlayDaG33k  https://github.com/tkyaji/cordova-plugin-crypt-file/issues/59 and it's help me

**Comment by FinlayDaG33k** [comment]
No problem :) 
would you mind closing this issue? :)
