### ISSUE TITLE
Build issue with firebase plugin in android

### ISSUE THREAD

**Issue by Kasun002** [tkyaji/cordova-plugin-crypt-file#81]
I have using firebase in my project using billow configeration
`    compile "com.google.firebase:firebase-core:16.0.8"
    compile "com.google.firebase:firebase-messaging:17.5.0"
    compile "com.google.firebase:firebase-config:16.4.1"
    compile "com.google.firebase:firebase-perf:16.2.4"`

When adding cript file plugin it gives an error like billows

`Error:The library com.google.firebase:firebase-iid is being requested by various other libraries at [[17.1.1,17.1.1]], but resolves to 19.0.0. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.`

**Comment by roushankumar01** [comment]
@Kasun002  have you find any solution related to issue?

**Comment by Kasun002** [comment]
@roushankumar01 It gives because of using Cordova firebase plugin [](https://github.com/arnesson/cordova-plugin-firebase) inside my project and some mismatch google services.
